
import "~/styles/styles.css";

import { GeistSans } from "geist/font/sans";

import { TRPCReactProvider } from "~/trpc/react";

import { AppContextProvider } from "./components/AppContext";

export const metadata = {
  title: "Martha Carter Therapy",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={GeistSans.className}>
          <TRPCReactProvider>
              {children}
          </TRPCReactProvider>
      </body>
    </html>
  );
}
